version: '3'
services:
  pg:
    image: postgres:11.7-alpine
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=thesprinters
      - POSTGRES_PASSWORD=thesprinters
      - POSTGRES_DB=thesprinters
    restart: always

volumes:
  config-volume:
